add danish lang
schedule-x/schedule-x pull request #217
Opened 2024-02-03 11:00 UTC by NoahBohme

## Checklist

Please put "X" in the below checkboxes that apply:

- [x] If committing a change of production code, I have tested it in different browsers (Chrome, Firefox, Safari). 
- [x] If committing a new feature, I have first submitted an issue (Please note: you are free to open PRs for non-issued features, but opening an issue increases your chance of a successful PR). 
- [x] If committing a new feature, I have also written the appropriate tests for it. 
- [x] I have tried to build the feature in a way, that it does not cause any breaking changes for others (unless 
  agreed upon in an issue). 

## This PR solves the following problem**. 

Add danish languge

2024-02-03 15:52 UTC, tomosterlund requested changes
Hey there. Thanks for wanting to contribute to the library! Just a few minor corrections, and we'd also need to add the full language from `packages/translations/src/locales/da-DK/index.ts` in `packages/translations/src/index.ts` where all translations come together.

Let me know if you need any help, or want me to finish it off :)

2024-02-03 15:52 UTC, tomosterlund commented on packages/translations/src/locales/da-DK/calendar.ts
> +export const calendarSvSE: CalendarTranslations = {
```suggestion
export const calendarDaDK: CalendarTranslations = {
```

2024-02-03 15:52 UTC, tomosterlund commented on packages/translations/src/locales/da-DK/date-picker.ts
> +export const datePickerSvSE: DatePickerTranslations = {
```suggestion
export const datePickerDaDK: DatePickerTranslations = {
```

2024-02-03 15:52 UTC, tomosterlund commented on packages/translations/src/locales/da-DK/index.ts
> +export const svSE: Language = {
```suggestion
export const daDK: Language = {
```

2024-02-09 19:23 UTC, merged

2024-02-09 21:29 UTC, NoahBohme commented
Thanks - sorry for the delay.

2024-02-09 21:38 UTC, tomosterlund commented
No worries! Thanks for adding the translations :)