feat: separate between Serbian with latin letters and cyrillic
schedule-x/schedule-x pull request #778
Opened 2024-11-13 19:16 UTC by tomosterlund

2024-11-13 19:18 UTC, tomosterlund commented
@alexva22 do you know the Cyrillic alphabet, or do you know anyone who does?

I just used Google translate for the Cyrillic version now, and have no good way of verifying that these translations are correct.

2024-11-14 07:20 UTC, alexva22 requested changes

2024-11-14 07:20 UTC, alexva22 commented on packages/translations/src/locales/sr-RS/calendar.ts
> +  Today: 'данас',
Данас

2024-11-14 07:20 UTC, alexva22 commented on packages/translations/src/locales/sr-RS/calendar.ts
> +  'Select View': 'Изаберите Виев',
Изаберите преглед

2024-11-14 07:20 UTC, alexva22 commented on packages/translations/src/locales/sr-RS/calendar.ts
> +  events: 'догађаји',
Догађаји

2024-11-14 07:20 UTC, alexva22 commented on packages/translations/src/locales/sr-RS/calendar.ts
> +  event: 'догађај',
Догађај

2024-11-14 07:20 UTC, alexva22 commented on packages/translations/src/locales/sr-RS/calendar.ts
> +    'Повежите са још {{n}} догађаја {{date}}',
Линк до још {{n}} догађаја на {{date}}

2024-11-14 07:20 UTC, alexva22 commented on packages/translations/src/locales/sr-RS/date-picker.ts
> +  Date: 'датум',
Датум

2024-11-14 07:20 UTC, alexva22 commented on packages/translations/src/locales/sr-RS/date-picker.ts
> +  'Next month': 'Следећег месеца',
Следећи месец

2024-11-15 05:49 UTC, merged